done
mate-academy/layout_antisnake pull request #1079
Opened 2022-03-09 22:56 UTC by misha200119

- [DEMO LINK](https://misha200119.github.io/layout_antisnake/)
- [TEST REPORT LINK](https://misha200119.github.io/layout_antisnake/report/html_report/)

2022-03-10 11:24 UTC, illiarerun requested changes
Good job 🔥 But your test link doesn't work,try to run them one more time and then deploy again

2022-03-10 11:24 UTC, illiarerun commented on src/styles/blocks/blocks-container.scss
> +    grid-template-columns: repeat(2,1fr);
```suggestion
    grid-template-columns: repeat(2, 1fr);
```

2022-03-10 11:24 UTC, illiarerun commented on src/styles/blocks/blocks-container.scss
> +    grid-template-columns: repeat(3,1fr);
```suggestion
    grid-template-columns: repeat(3, 1fr);
```

2022-03-10 11:24 UTC, illiarerun commented on src/styles/blocks/block.scss
> +      background-color: rgb(calc(#{255 * (6 - $index) / 5}), 0, 0);
you could've used % values for colors, like 100% - ((index - 1) * 20%)

2022-03-11 10:45 UTC, Ihor-Karpyn approved these changes

2025-01-03 14:21 UTC, closed without merging