antisnake
mate-academy/layout_antisnake pull request #1201
Opened 2022-05-12 11:55 UTC by vsupruniuk

- [DEMO LINK](https://vsupruniuk.github.io/layout_antisnake/)
- [TEST REPORT LINK](https://vsupruniuk.github.io/layout_antisnake/report/html_report/)

2022-05-13 12:05 UTC, stanislav-topikha requested changes
Good job! But there is no test report.

2022-05-13 12:05 UTC, stanislav-topikha commented on src/styles/blocks/snake.scss
> +  }
You can put modifiers into the element

2022-05-13 12:16 UTC, stanislav-topikha approved these changes

2022-05-16 12:57 UTC, Olexandr6 requested changes
Your solution is good, but can be improved; Let's do this🔥

2022-05-16 12:57 UTC, Olexandr6 commented on src/styles/blocks/snake.scss
> +  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
🔥

2022-05-16 12:57 UTC, Olexandr6 commented on src/styles/blocks/snake.scss
> +    height: 300px;
You use 300px in several places, so let's create an`scss` variable for this.

2022-05-16 12:57 UTC, Olexandr6 commented on src/styles/blocks/snake.scss
> +    }
Let's find another solution for this logic. Don't create additional classes. Here you have almost the same styles for every class.

Hint: use `nth-child: ` + `@for` cylce

2022-05-17 09:42 UTC, Olexandr6 approved these changes
Great fob🔥

2022-05-17 09:42 UTC, Olexandr6 commented on src/styles/blocks/snake.scss
> +        background: mix(#f00, #000, 100 - 20 * ($var - 1));
🔥

2024-01-13 13:25 UTC, closed without merging