add antisnake
mate-academy/layout_antisnake pull request #1213
Opened 2022-05-16 21:02 UTC by Pavlo000

- [DEMO LINK](https://Pavlo000.github.io/layout_antisnake/)
- [TEST REPORT LINK](https://Pavlo000.github.io/layout_antisnake/report/html_report/)

2022-05-18 13:09 UTC, liliia-livandovskaya commented on src/styles/blocks/block.scss
> +      min-height: $size-cell;
класно!

2022-05-18 13:15 UTC, liliia-livandovskaya approved these changes
Гарна робота. Єдиний момент: при перегляді на екрані більш ніж 1200 блоки мають розтягуватись на всю ширину екрана.

2022-05-19 11:54 UTC, Olexandr6 requested changes
Almost done👍

2022-05-19 11:54 UTC, Olexandr6 commented on src/styles/blocks/container.scss
> +  max-width: 1199px;
Don't set max-width, @liliia-livandovskaya is right

2022-05-19 11:54 UTC, Olexandr6 commented on src/index.html
> +      <div class="block block--1"></div>
Let's don't create additional classes, use `:nth-child` instead

2022-05-19 12:23 UTC, Olexandr6 requested changes

2022-05-19 12:23 UTC, Olexandr6 commented on src/styles/blocks/block.scss
> +      color: white;
These styles should be moved to `.block`

2022-05-19 12:23 UTC, Olexandr6 commented on src/styles/blocks/block.scss
> +      font-family: Arial, Helvetica, sans-serif;
Move to normalize.scss

2022-05-19 12:23 UTC, Olexandr6 commented on src/styles/main.scss
> +body:nth-child(n) {
Omg, don't do so, create a div container for this purpose

2022-05-19 12:23 UTC, Olexandr6 commented on src/styles/main.scss
> +body:nth-child(n) {
Why do you set `grid` for all body children?

2022-05-22 10:13 UTC, Olexandr6 approved these changes
Much better🔥

2024-11-26 18:14 UTC, closed without merging