antisnake created
mate-academy/layout_antisnake pull request #1237
Opened 2022-05-19 13:25 UTC by KrisMur

- [DEMO LINK](https://KrisMur.github.io/layout_antisnake/)
- [TEST REPORT LINK](https://KrisMur.github.io/layout_antisnake/report/html_report/)

2022-05-19 13:56 UTC, ostapfriend requested changes
Все ідеально зроблено,молодець. Лише є один момент.

2022-05-19 13:56 UTC, ostapfriend commented on src/styles/utils/_normalise.scss
> +}
Використовувати зірочку погана ідея.  І тобі не потрібно ніяких border-box тут

2022-05-19 14:06 UTC, ostapfriend approved these changes

2022-05-19 14:06 UTC, ostapfriend commented
Круто)

2022-05-20 12:35 UTC, mykola-koval approved these changes

2022-05-20 12:35 UTC, mykola-koval commented on src/styles/utils/_variables.scss
> +  "1" rgb(255,0,0),
you can use percentages with rgb
```suggestion
  "1" rgb(100%,0,0),
```

2024-10-19 12:31 UTC, closed without merging