Solution
mate-academy/layout_antisnake pull request #262
Opened 2020-05-04 10:25 UTC by V2473

- [DEMO LINK](https://V2473.github.io/layout_antisnake/)
- [TEST REPORT LINK](https://V2473.github.io/layout_antisnake/report/html_report/)

2020-05-04 11:15 UTC, liliya-dev requested changes

2020-05-04 11:15 UTC, liliya-dev commented on src/styles/main.scss
> +    color: white;
use variable to write the color

2020-05-04 12:33 UTC, liliya-dev approved these changes

2020-05-06 07:10 UTC, mriynyk approved these changes

2025-07-18 15:08 UTC, closed without merging