layout_antisnake PR
mate-academy/layout_antisnake pull request #750
Opened 2021-08-28 19:08 UTC by Rocketjet

- [DEMO LINK](https://Rocketjet.github.io/layout_antisnake/)

2021-08-29 19:11 UTC, caelum29 requested changes

2021-08-29 19:11 UTC, caelum29 commented on src/index.html
> +      <div class="container__box container_box_6">6</div>
по бему должно быть так container__box--1 (если я не ошибаюсь )

2021-08-29 19:13 UTC, Rocketjet commented on src/index.html
> +      <div class="container__box container_box_6">6</div>
Помиляєшся)
https://ru.bem.info/methodology/naming-convention/

2021-08-29 19:21 UTC, caelum29 approved these changes

2021-08-29 19:22 UTC, caelum29 commented on src/index.html
> +      <div class="container__box container_box_6">6</div>
`<div class="container__box container__box_1">1</div>` тоді моє бути ось так?

2021-08-29 19:48 UTC, Rocketjet commented on src/index.html
> +      <div class="container__box container_box_6">6</div>
Так, ти правий, але я не можу зробити такий запис, лінтер не дає:
![image](https://user-images.githubusercontent.com/24256475/131263493-63b01c7e-b511-4057-964e-cf4ac8654f65.png)

2021-08-29 19:51 UTC, caelum29 commented on src/index.html
> +      <div class="container__box container_box_6">6</div>
в мене теж таку помилку викидує

2021-08-29 19:55 UTC, caelum29 commented on src/index.html
> +      <div class="container__box container_box_6">6</div>
`<div class="container__block container__block--1">1</div>` спробуй ось так

2021-08-29 20:04 UTC, Rocketjet commented on src/index.html
> +      <div class="container__box container_box_6">6</div>
Заканало. Значить треба буде правити файл лінтера під свій варіант найменування.

2021-08-30 09:04 UTC, Ihor-Karpyn approved these changes
LGTM

2024-05-29 15:33 UTC, closed without merging