Antisnake Homework
mate-academy/layout_antisnake pull request #84
Opened 2019-07-29 20:07 UTC by amserhii11

- [UPDATE DEMO LINK](https://amserhii11.github.io/layout_antisnake/)
- [UPDATE TEST REPORT LINK](https://amserhii11.github.io/layout_antisnake/report/html_report/)

2019-07-31 10:49 UTC, danheim requested changes
Fix indents and use repeat()

2019-07-31 10:49 UTC, danheim commented on src/index.html
> +  1
indent

2019-07-31 10:49 UTC, danheim commented on src/index.html
> +  2
indent

2019-07-31 10:49 UTC, danheim commented on src/index.html
> +  3
indent

2019-07-31 10:49 UTC, danheim commented on src/index.html
> +  4
indent

2019-07-31 10:49 UTC, danheim commented on src/index.html
> +  5
indent

2019-07-31 10:49 UTC, danheim commented on src/index.html
> +  6
indent

2019-07-31 10:49 UTC, danheim commented on src/index.html
> +<div class="snake-layout">
indent

2019-07-31 10:49 UTC, danheim commented on src/style.css
> +  grid-template-rows: 300px 300px 300px;
use repeat()

2019-07-31 10:49 UTC, danheim commented on src/style.css
> +  grid-template-columns: 1fr 1fr 1fr;
use repeat()

2019-07-31 10:49 UTC, danheim commented on src/style.css
> +    grid-template-rows: 300px 300px 300px 300px 300px 300px;
use repeat()

2019-07-31 14:54 UTC, irenhh requested changes
Indentations were not fixed

2019-08-01 10:39 UTC, danheim approved these changes

2025-09-02 14:50 UTC, closed without merging