Done
mate-academy/layout_antisnake pull request #926
Opened 2021-11-29 13:41 UTC by MaksimusCRS

- [DEMO LINK](https://MaksimusCRS.github.io/layout_antisnake/)
- [TEST REPORT LINK](https://MaksimusCRS.github.io/layout_antisnake/report/html_report/)

2021-11-29 13:45 UTC, luckdenny commented on src/index.html
> +      <div class="antisnake__block antisnake__block--6">6</div>
можно было как в задании с календарем закинуть контент цифр циклом

2021-11-29 13:48 UTC, luckdenny commented on src/styles/main.scss
> +    min-width: 300px;
мне кажется ширину не обязательно

2021-11-29 13:48 UTC, luckdenny approved these changes

2021-11-29 13:51 UTC, MaksimusCRS commented on src/styles/main.scss
> +    min-width: 300px;
Там в задании сказано, что нужно)
- The width of each block should be not less than its height (`300px`)

2021-11-29 13:51 UTC, MaksimusCRS commented on src/index.html
> +      <div class="antisnake__block antisnake__block--6">6</div>
Согласен, можно было через ::befor сделать )

2021-11-29 16:44 UTC, Elena-brv requested changes

2021-11-29 16:44 UTC, Elena-brv commented on src/styles/main.scss
> +    min-width: 300px;
use grid properties on container not to specify min-width here

2021-11-29 16:44 UTC, Elena-brv commented on src/styles/main.scss
>  }
do this task with only 1 media query. The is no sense of grid with so many media queries. And use nesting for media

2021-11-29 16:44 UTC, Elena-brv commented on src/styles/main.scss
> +      &--#{$name} {
use nth-child instead of modificators

2021-11-30 09:36 UTC, luckdenny approved these changes

2021-11-30 16:20 UTC, Elena-brv approved these changes

2021-11-30 16:20 UTC, Elena-brv commented on src/styles/main.scss
>  }
```suggestion

  @media (min-width: 1200px) {
    grid-template-columns: repeat(3, 1fr);
  }
}
```

2022-10-20 17:52 UTC, closed without merging