solution
mate-academy/layout_antisnake pull request #951
Opened 2021-12-21 11:48 UTC by ivan-major

2021-12-21 13:42 UTC, varseniuk submitted a review, later dismissed
На широких екранах виглядає некоректно. Має ьути 3 колонки і ширина блоків має розтягуватись

2021-12-21 13:42 UTC, varseniuk commented on src/styles/main.scss
> +      &--#{$number} {
Замість того, щоб створювати безліч класів із цифрами, краще використовувати псевдоклас :nth-child

2021-12-21 13:42 UTC, varseniuk commented on readme.md
> +- [TEST REPORT LINK](https://ivan-major.github.io/layout_antisnake/report/html_report/)
Тести не задеплоїлись. Ти запускав npm test перед деплоєм?

2021-12-21 15:25 UTC, vkryvytskyy requested changes

2021-12-21 15:25 UTC, vkryvytskyy commented on readme.md
> +- [TEST REPORT LINK](https://ivan-major.github.io/layout_antisnake/report/html_report/)
![image](https://user-images.githubusercontent.com/38065883/146955152-c2f446fe-bd29-4e69-9d2b-fd3c613046e8.png)
Запускал `npm run deploy`? Тут старая версия все еще, где один ряд

2021-12-21 17:44 UTC, ivan-major commented on readme.md
> +- [TEST REPORT LINK](https://ivan-major.github.io/layout_antisnake/report/html_report/)
Запустив npm run deploy.
Можете знову подивитись

2021-12-22 11:47 UTC, vkryvytskyy approved these changes

2025-01-26 13:02 UTC, closed without merging